/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package warnetapp.member;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import warnetapp.DBConnection;
import javax.swing.ImageIcon;

/**
 *
 * @author rajaa
 */
public class DashboardMember extends javax.swing.JFrame {
    private String loggedUsername;
    private int sisaDetik;
    private javax.swing.Timer timer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardMember.class.getName());

    /**
     * Creates new form dashboardMember
     */
    public DashboardMember(String username) {
        setIconImage(new ImageIcon(getClass().getResource("/images/logo.jpeg")).getImage());
        initComponents();
            this.loggedUsername = username;
            lblUser.setText(username.toUpperCase() + "!");
            loadSisaWaktu();
            startTimer();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void startTimer(){
           timer = new javax.swing.Timer(1000, e -> {
        if (sisaDetik > 0) {
            sisaDetik--;
            int jam = sisaDetik / 3600;
            int menit = (sisaDetik % 3600) / 60;
            int detik = sisaDetik % 60;
            lblTime.setText(String.format("%02d : %02d : %02d", jam, menit, detik));
            if (sisaDetik % 10 == 0) {
                simpanSisaWaktu();
            }
        } else {
            timer.stop();
            lblTime.setText("00 : 00 : 00");
            javax.swing.JOptionPane.showMessageDialog(
                this, "Waktu habis!", "Info",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            MemberLogin logout = new warnetapp.member.MemberLogin();
            logout.setVisible(true);
            logout.setLocationRelativeTo(null);
            this.dispose();
            
        }
    });
    timer.start();
    }  
    
    private void loadSisaWaktu(){
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                "SELECT saldo_menit FROM member WHERE username = ?"
            );

            ps.setString(1, loggedUsername);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                sisaDetik = rs.getInt("saldo_menit") * 60;
            }
        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    private void simpanSisaWaktu(){
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                    "UPDATE member SET saldo_menit = ? WHERE username = ?"
            );
            ps.setInt(1, (int) Math.ceil(sisaDetik / 60.0));
            ps.setString(2,loggedUsername);
            
            ps.executeUpdate();
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblNameWarnet = new javax.swing.JLabel();
        lblVisiMisi = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        panelTimeWrapper = new javax.swing.JPanel();
        panelTime = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblRemainingTime = new javax.swing.JLabel();
        txtCodeReedem = new javax.swing.JTextField();
        lblCodeReedem = new javax.swing.JLabel();
        btnReedem = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(69, 46, 90));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(30, 16, 78));

        lblNameWarnet.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lblNameWarnet.setForeground(new java.awt.Color(255, 101, 63));
        lblNameWarnet.setText("UcupWarnet");

        lblVisiMisi.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        lblVisiMisi.setForeground(new java.awt.Color(255, 200, 92));
        lblVisiMisi.setText("Best Warnet In The World");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNameWarnet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVisiMisi)
                .addGap(137, 137, 137))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVisiMisi)
                    .addComponent(lblNameWarnet))
                .addContainerGap())
        );

        jPanel2.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        lblWelcome.setBackground(new java.awt.Color(0, 0, 0));
        lblWelcome.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("SELAMAT DATANG");
        jPanel2.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        panelTimeWrapper.setBackground(new java.awt.Color(204, 204, 204));

        lblTime.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("TIMER");
        lblTime.setToolTipText("");

        javax.swing.GroupLayout panelTimeLayout = new javax.swing.GroupLayout(panelTime);
        panelTime.setLayout(panelTimeLayout);
        panelTimeLayout.setHorizontalGroup(
            panelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTimeLayout.setVerticalGroup(
            panelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblRemainingTime.setText("SISA WAKTU");

        javax.swing.GroupLayout panelTimeWrapperLayout = new javax.swing.GroupLayout(panelTimeWrapper);
        panelTimeWrapper.setLayout(panelTimeWrapperLayout);
        panelTimeWrapperLayout.setHorizontalGroup(
            panelTimeWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTimeWrapperLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(lblRemainingTime)
                .addGap(123, 123, 123))
            .addComponent(panelTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTimeWrapperLayout.setVerticalGroup(
            panelTimeWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTimeWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRemainingTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(panelTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelTimeWrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 330, 80));
        jPanel2.add(txtCodeReedem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, -1));

        lblCodeReedem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodeReedem.setForeground(new java.awt.Color(255, 255, 255));
        lblCodeReedem.setText("Code Reedem :");
        jPanel2.add(lblCodeReedem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        btnReedem.setBackground(new java.awt.Color(51, 255, 51));
        btnReedem.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        btnReedem.setForeground(new java.awt.Color(255, 255, 255));
        btnReedem.setText("Reedem");
        btnReedem.addActionListener(this::btnReedemActionPerformed);
        jPanel2.add(btnReedem, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 200, 80, -1));

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, -1));

        btnChangePassword.setBackground(new java.awt.Color(0, 0, 255));
        btnChangePassword.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(this::btnChangePasswordActionPerformed);
        jPanel2.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 140, -1));

        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("{User}");
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        timer.stop();
        simpanSisaWaktu();
        MemberLogin logout = new warnetapp.member.MemberLogin();
        logout.setVisible(true);
        logout.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnReedemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReedemActionPerformed
        // TODO add your handling code here:
        String code = txtCodeReedem.getText().trim();
        
        
       if (code.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this,
                "Masukkan kode redeem dulu!",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return; 
       }
       
       try {
           Connection conn =  DBConnection.getConnection();
           
           PreparedStatement ps = conn.prepareStatement(
                   "SELECT * FROM redeem_code WHERE kode = ? AND status = 'unused'"
           );
           ps.setString(1,code);
           ResultSet rs = ps.executeQuery();
           
           if(rs.next()){
               int tambahMenit = rs.getInt("tambah_menit");
               PreparedStatement psUsed = conn.prepareStatement(
                       "UPDATE redeem_code SET status = 'used' WHERE kode = ?"
               );
               psUsed.setString(1,code);
               psUsed.executeUpdate();
               
               PreparedStatement psAdd = conn.prepareStatement(
                       "UPDATE member SET saldo_menit = saldo_menit + ? WHERE username = ?"
               );
                psAdd.setInt(1, tambahMenit);
                psAdd.setString(2, loggedUsername);
                psAdd.executeUpdate();
                
                sisaDetik += tambahMenit * 60;
                txtCodeReedem.setText("");
                
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Berhasil +" + (tambahMenit / 60) + "Jam di Tambahkan!",
                        "Redeem Berhasil!",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
           }else {
               javax.swing.JOptionPane.showMessageDialog(this,
                       "Kode tidak valid atau sudah di pakai",
                       "Gagal",
                       javax.swing.JOptionPane.ERROR_MESSAGE);               
           }
       }catch(SQLException e){
           System.out.println("Error : " + e.getMessage());
       }
    }//GEN-LAST:event_btnReedemActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        ForgotPasswordMember change = new ForgotPasswordMember();
                change.setVisible(true);
                change.setLocationRelativeTo(null);
                
    }//GEN-LAST:event_btnChangePasswordActionPerformed


    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardMember("test").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReedem;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCodeReedem;
    private javax.swing.JLabel lblNameWarnet;
    private javax.swing.JLabel lblRemainingTime;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVisiMisi;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelTime;
    private javax.swing.JPanel panelTimeWrapper;
    private javax.swing.JTextField txtCodeReedem;
    // End of variables declaration//GEN-END:variables
}
