/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package warnetapp.member;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import warnetapp.DBConnection;
import javax.swing.ImageIcon;
/**
 *
 * @author rajaa
 */
public class ForgotPasswordMember extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPasswordMember.class.getName());

    /**
     * Creates new form forgotPasswordMember
     */
    public ForgotPasswordMember() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/logo.jpeg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblNoHP = new javax.swing.JLabel();
        txtNoHP = new javax.swing.JTextField();
        lblNewPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        lblAlert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ganti Password");

        jPanel1.setBackground(new java.awt.Color(69, 46, 90));

        jPanel2.setBackground(new java.awt.Color(30, 16, 78));
        jPanel2.setForeground(new java.awt.Color(30, 16, 78));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 200, 92));
        jLabel1.setText("CHANGE YOUR ");

        jLabel5.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("PASSWORD");

        jLabel2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pergi Ke Admin Untuk Membuat Akun");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUsername.setForeground(new java.awt.Color(255, 200, 92));
        lblUsername.setText("Username :");

        lblNoHP.setForeground(new java.awt.Color(255, 200, 92));
        lblNoHP.setText("No.HP :");

        lblNewPassword.setForeground(new java.awt.Color(255, 200, 92));
        lblNewPassword.setText("New Password :");

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        btnChange.setBackground(new java.awt.Color(51, 255, 51));
        btnChange.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnChange.setForeground(new java.awt.Color(255, 255, 255));
        btnChange.setText("Change Password");
        btnChange.addActionListener(this::btnChangeActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNewPassword)
                    .addComponent(lblNoHP)
                    .addComponent(lblUsername)
                    .addComponent(txtNoHP)
                    .addComponent(txtUsername)
                    .addComponent(txtNewPassword)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblNoHP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNewPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText().trim();
        String noHp = txtNoHP.getText().trim();
        String newPassword = txtNewPassword.getText().trim();
        
        if(username.isEmpty() && noHp.isEmpty() && newPassword.isEmpty()) {
            lblAlert.setVisible(true);
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("Username, NoHP & Password Tidak Boleh Kosong");
            return;
        }
        
        if(username.isEmpty() && noHp.isEmpty()) {
            lblAlert.setVisible(true);
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("Username & NoHP Tidak Boleh Kosong");
            return;
        }
        
        if(username.isEmpty() && newPassword.isEmpty()) {
            lblAlert.setVisible(true);
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("Username & Password Tidak Boleh Kosong");
            return;
        }
        
        if(noHp.isEmpty() && newPassword.isEmpty()) {
            lblAlert.setVisible(true);
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("NoHP & Password Tidak Boleh Kosong");
            return;
        }
        
        if(username.isEmpty()){
            lblAlert.setVisible(true);
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("Username Tidak Boleh Kosong");
            return;
        }
        
        if(noHp.isEmpty()){
            lblAlert.setVisible(true);
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("NoHP Tidak Boleh Kosong");
            return;
        }
        
        if(newPassword.isEmpty()){
            lblAlert.setVisible(true);
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("Password Tidak Boleh Kosong");
            return;
        }
        if (newPassword.contains(" ")) {
            lblAlert.setVisible(true);
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("Password Tidak Boleh Mengandung Spasi");
            return;
        }
        
        try {
            Connection conn = DBConnection.getConnection();
            String query = "SELECT * FROM member WHERE username = ? AND no_hp = ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, username);
            ps.setLong(2, Long.parseLong(noHp));
            ResultSet rs = ps.executeQuery();

            if (!rs.next()) {
                PreparedStatement psUser = conn.prepareStatement(
                    "SELECT * FROM member WHERE username = ?"
                );
                psUser.setString(1, username);
                ResultSet rsUser = psUser.executeQuery();

                if (!rsUser.next()) {
                    lblAlert.setVisible(true);
                    lblAlert.setForeground(java.awt.Color.RED);
                    lblAlert.setText("User Tidak di Temukan!");
                } else {
                    lblAlert.setVisible(true);
                    lblAlert.setForeground(java.awt.Color.RED);
                    lblAlert.setText("No.Hp SALAH!");
                }
                return;
            }

            
            PreparedStatement psUpdate = conn.prepareStatement(
                "UPDATE member SET password = ? WHERE username = ?"
            );
            psUpdate.setString(1, newPassword);
            psUpdate.setString(2, username);
            psUpdate.executeUpdate();

            // pw berhasil di ganti
            lblAlert.setForeground(java.awt.Color.GREEN);
            lblAlert.setText("*Password berhasil diubah!");
            lblAlert.setVisible(true);
            txtUsername.setText("");
            txtNoHP.setText("");
            txtNewPassword.setText("");

            } catch (NumberFormatException e) {
                lblAlert.setForeground(java.awt.Color.RED);
                lblAlert.setText("*No.HP harus berupa angka!");
                lblAlert.setVisible(true);
            } catch (SQLException e) {
                lblAlert.setForeground(java.awt.Color.RED);
                lblAlert.setText("*Error: " + e.getMessage());
                lblAlert.setVisible(true);
            }
    

        
        
        
        
    }//GEN-LAST:event_btnChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPasswordMember().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAlert;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblNoHP;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtNoHP;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
