/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package warnetapp.member;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import warnetapp.DBConnection;
import javax.swing.ImageIcon;
/**
 *
 * @author rajaa
 */
public class MemberLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MemberLogin.class.getName());

    /**
     * Creates new form memberLogin
     */
    public MemberLogin() {
        initComponents();
        lblAlert.setVisible(false);
        setIconImage(new ImageIcon(getClass().getResource("/images/logo.jpeg")).getImage());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        headerMemberLogin = new javax.swing.JPanel();
        lblNameWarnet = new javax.swing.JLabel();
        lblVisiMisi = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnForgetPassword = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblAlert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        panelContent.setBackground(new java.awt.Color(69, 46, 90));

        headerMemberLogin.setBackground(new java.awt.Color(30, 16, 78));

        lblNameWarnet.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lblNameWarnet.setForeground(new java.awt.Color(255, 101, 63));
        lblNameWarnet.setText("UcupWarnet");

        lblVisiMisi.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        lblVisiMisi.setForeground(new java.awt.Color(255, 200, 92));
        lblVisiMisi.setText("Best Warnet In The World");

        javax.swing.GroupLayout headerMemberLoginLayout = new javax.swing.GroupLayout(headerMemberLogin);
        headerMemberLogin.setLayout(headerMemberLoginLayout);
        headerMemberLoginLayout.setHorizontalGroup(
            headerMemberLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerMemberLoginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblNameWarnet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVisiMisi)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        headerMemberLoginLayout.setVerticalGroup(
            headerMemberLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerMemberLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerMemberLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVisiMisi)
                    .addComponent(lblNameWarnet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblUsername.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 200, 92));
        lblUsername.setText("Username :");

        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        lblPassword.setBackground(new java.awt.Color(255, 200, 92));
        lblPassword.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 200, 92));
        lblPassword.setText("Password :");

        btnForgetPassword.setBackground(new java.awt.Color(0, 0, 255));
        btnForgetPassword.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        btnForgetPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnForgetPassword.setText("Forgot Password");
        btnForgetPassword.addActionListener(this::btnForgetPasswordActionPerformed);

        btnLogin.setBackground(new java.awt.Color(0, 255, 0));
        btnLogin.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblAlert.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addComponent(headerMemberLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelContentLayout.createSequentialGroup()
                        .addComponent(btnForgetPassword)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addComponent(headerMemberLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnForgetPassword)
                    .addComponent(btnLogin))
                .addGap(25, 25, 25))
        );

        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());
        
        if (username.isEmpty() && password.isEmpty()) {
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("*Username dan password Tidak Boleh Kosong");
            lblAlert.setVisible(true);
            return;
        }
        
        if (username.isEmpty()) {
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("*Username Harus Di isi!!");
            lblAlert.setVisible(true);
            return;
        }
        
        if (password.isEmpty()) {
            lblAlert.setForeground(java.awt.Color.RED);
            lblAlert.setText("*Password Harus Di isi!!");
            lblAlert.setVisible(true);
            return;
        }        
        
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                "SELECT * FROM member WHERE username = ? AND password = ?"
            ); 
            
            ps.setString(1, username);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    // Login berhasil → kirim username ke dashboard
                    DashboardMember dashboard = new DashboardMember(username);
                    dashboard.setVisible(true);
                    dashboard.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    lblAlert.setForeground(java.awt.Color.RED);
                    lblAlert.setText("*Username atau Password salah!");
                    lblAlert.setVisible(true);
                }
            } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
            }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnForgetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetPasswordActionPerformed
        // TODO add your handling code here:
        ForgotPasswordMember frame = new ForgotPasswordMember();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_btnForgetPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MemberLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgetPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel headerMemberLogin;
    private javax.swing.JLabel lblAlert;
    private javax.swing.JLabel lblNameWarnet;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblVisiMisi;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
