/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package warnetapp.admin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import warnetapp.DBConnection;
import java.util.Random;
import javax.swing.ImageIcon;
/**
 *
 * @author rajaa
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());
    
    /**
     * Creates new form dashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/logo.jpeg")).getImage());
        loadMember("");
        loadKode();
        TabbedPane.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int runCount, int maxTabHeight) {
                return 0;
            }

            @Override
            protected void paintContentBorder(java.awt.Graphics g, int tabPlacement, int selectedIndex) {
                    
            }

            @Override
            protected java.awt.Insets getContentBorderInsets(int tabPlacement) {
                return new java.awt.Insets(0, 0, 0, 0); 
            }
    });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDuration = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        navbar = new javax.swing.JPanel();
        btnBuatMember = new javax.swing.JButton();
        btnLihatMember = new javax.swing.JButton();
        btnTambahBilling = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        TabbedPane = new javax.swing.JTabbedPane();
        panelAbout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelCreateAccount = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        alertLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelSeeMember = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();
        panelAddBilling = new javax.swing.JPanel();
        rb1Jam = new javax.swing.JRadioButton();
        rb3Jam = new javax.swing.JRadioButton();
        rb5Jam = new javax.swing.JRadioButton();
        rb10Jam = new javax.swing.JRadioButton();
        btnGenerate = new javax.swing.JButton();
        txtCode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCode = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnRefreshCode = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DashBoard Admin - About");

        navbar.setBackground(new java.awt.Color(51, 51, 51));

        btnBuatMember.setBackground(new java.awt.Color(0, 204, 0));
        btnBuatMember.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        btnBuatMember.setForeground(new java.awt.Color(255, 255, 255));
        btnBuatMember.setText("BUAT AKUN MEMBER");
        btnBuatMember.addActionListener(this::btnBuatMemberActionPerformed);

        btnLihatMember.setBackground(new java.awt.Color(51, 102, 255));
        btnLihatMember.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        btnLihatMember.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatMember.setText("LIHAT MEMBER");
        btnLihatMember.addActionListener(this::btnLihatMemberActionPerformed);

        btnTambahBilling.setBackground(new java.awt.Color(204, 204, 0));
        btnTambahBilling.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        btnTambahBilling.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahBilling.setText("GENERATE CODE REEDEM");
        btnTambahBilling.addActionListener(this::btnTambahBillingActionPerformed);

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnAbout.setBackground(new java.awt.Color(204, 204, 204));
        btnAbout.setText("About");
        btnAbout.addActionListener(this::btnAboutActionPerformed);

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahBilling, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLihatMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuatMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuatMember, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLihatMember, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambahBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(27, 27, 27))
        );

        TabbedPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                TabbedPaneComponentMoved(evt);
            }
        });

        jLabel1.setText("Selamat Datang Di aplikasi WarnetApp.");

        jLabel2.setText("Aplikasi Ini di rancang untuk memenuhi persyaratan Ujian akhir semester ");

        jLabel3.setText("dibuat oleh : Raja Antawijaya");

        jLabel5.setText("dirancang oleh : Mamay & Dirga");

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(387, 387, 387))
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(30, 30, 30))
        );

        TabbedPane.addTab("About", panelAbout);

        jLabel8.setText("Username :");

        txtUser.addActionListener(this::txtUserActionPerformed);

        txtPhoneNumber.addActionListener(this::txtPhoneNumberActionPerformed);

        jLabel9.setText("No. HP :");

        btnCreateAccount.setBackground(new java.awt.Color(51, 255, 51));
        btnCreateAccount.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(this::btnCreateAccountActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*Password Otomatis Di isi angka \"1\"");

        alertLabel.setForeground(new java.awt.Color(255, 51, 51));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(54, 133, 235));
        jLabel7.setText("*note = PEMBUATAN AKUN SUDAH FREE 10JAM BILLING");

        javax.swing.GroupLayout panelCreateAccountLayout = new javax.swing.GroupLayout(panelCreateAccount);
        panelCreateAccount.setLayout(panelCreateAccountLayout);
        panelCreateAccountLayout.setHorizontalGroup(
            panelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateAccountLayout.createSequentialGroup()
                .addGroup(panelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCreateAccountLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(panelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCreateAccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(panelCreateAccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        panelCreateAccountLayout.setVerticalGroup(
            panelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateAccountLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(15, 15, 15))
        );

        TabbedPane.addTab("CreateMember", panelCreateAccount);

        jLabel6.setText("Cari :");

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "no", "Username", "no.HP", "Waktu Billing"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMember);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnDeleteMember.setText("Delete Member");
        btnDeleteMember.addActionListener(this::btnDeleteMemberActionPerformed);

        javax.swing.GroupLayout panelSeeMemberLayout = new javax.swing.GroupLayout(panelSeeMember);
        panelSeeMember.setLayout(panelSeeMemberLayout);
        panelSeeMemberLayout.setHorizontalGroup(
            panelSeeMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeeMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSeeMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeeMemberLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeeMemberLayout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteMember)))
                .addGap(20, 20, 20))
        );
        panelSeeMemberLayout.setVerticalGroup(
            panelSeeMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeeMemberLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelSeeMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSeeMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteMember)
                    .addComponent(btnRefresh))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TabbedPane.addTab("SeeMember", panelSeeMember);

        bgDuration.add(rb1Jam);
        rb1Jam.setText("1  Jam - Rp5.000");
        rb1Jam.addActionListener(this::rb1JamActionPerformed);

        bgDuration.add(rb3Jam);
        rb3Jam.setText("3 Jam - Rp15.000");
        rb3Jam.addActionListener(this::rb3JamActionPerformed);

        bgDuration.add(rb5Jam);
        rb5Jam.setText("5 Jam - Rp25.000");

        bgDuration.add(rb10Jam);
        rb10Jam.setText("10 Jam - Rp.50.000");

        btnGenerate.setText("Generate Code");
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);

        txtCode.addActionListener(this::txtCodeActionPerformed);

        jLabel11.setText("Code :");

        tblCode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "no.", "Kode", "Durasi", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCode);

        btnRefreshCode.setText("Refresh Table");
        btnRefreshCode.addActionListener(this::btnRefreshCodeActionPerformed);

        javax.swing.GroupLayout panelAddBillingLayout = new javax.swing.GroupLayout(panelAddBilling);
        panelAddBilling.setLayout(panelAddBillingLayout);
        panelAddBillingLayout.setHorizontalGroup(
            panelAddBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddBillingLayout.createSequentialGroup()
                        .addGroup(panelAddBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rb3Jam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb5Jam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb10Jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rb1Jam, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(348, 348, 348))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddBillingLayout.createSequentialGroup()
                        .addGroup(panelAddBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAddBillingLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRefreshCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel12)
                .addGap(11, 11, 11))
        );
        panelAddBillingLayout.setVerticalGroup(
            panelAddBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb1Jam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb3Jam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb5Jam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb10Jam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAddBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddBillingLayout.createSequentialGroup()
                        .addGap(18, 116, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(72, 72, 72))
                    .addGroup(panelAddBillingLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelAddBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshCode)
                .addContainerGap())
        );

        TabbedPane.addTab("GenerateCodeReedem", panelAddBilling);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuatMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatMemberActionPerformed
        // TODO add your handling code here:
        TabbedPane.setSelectedIndex(1);
        setTitle("Dashboard Admin - Buat Akun Member");
        
    }//GEN-LAST:event_btnBuatMemberActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        AdminLogin logout = new warnetapp.admin.AdminLogin();
        logout.setVisible(true);
        logout.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void TabbedPaneComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TabbedPaneComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneComponentMoved

    private void btnLihatMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatMemberActionPerformed
        // TODO add your handling code here:
        TabbedPane.setSelectedIndex(2);
        setTitle("Dashboard Admin - Lihat Member");
    }//GEN-LAST:event_btnLihatMemberActionPerformed

    private void btnTambahBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBillingActionPerformed
        // TODO add your handling code here:
        TabbedPane.setSelectedIndex(3);
        setTitle("Dashboard Admin - Generate CodeReedem");
    }//GEN-LAST:event_btnTambahBillingActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        TabbedPane.setSelectedIndex(0);
        setTitle("Dashboard Admin - About");
    }//GEN-LAST:event_btnAboutActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
            String username = txtUser.getText().trim();
        String noHp = txtPhoneNumber.getText().trim();
        String password = "1";
        int saldoMenit = 600;

        // Validasi kosong

        if (username.isEmpty() && noHp.isEmpty()) {
            alertLabel.setForeground(java.awt.Color.RED);
            alertLabel.setText("*Username & Nomor HP tidak boleh kosong!");
            alertLabel.setVisible(true);
            return;
        }
        
        if (username.isEmpty()){
            alertLabel.setForeground(java.awt.Color.RED);
            alertLabel.setText("*Username tidak boleh kosong!");
            alertLabel.setVisible(true);
            return;
        }
        
        if (noHp.isEmpty()){
            alertLabel.setForeground(java.awt.Color.RED);
            alertLabel.setText("Nomor HP tidak boleh kosong!");
            alertLabel.setVisible(true);
            return;
        }
        // validasi mengandung spasi
        if (username.contains(" ")) {
            alertLabel.setForeground(java.awt.Color.RED);
            alertLabel.setText("*Username tidak boleh mengandung spasi!");
            alertLabel.setVisible(true);
            txtUser.setText("");
            return;
        }
        //Validasi ANgka
        if (!noHp.matches("[0-9]+")) {
            alertLabel.setForeground(java.awt.Color.RED);
            alertLabel.setText("*No HP tidak valid! Hanya boleh angka.");
            alertLabel.setVisible(true);
            txtPhoneNumber.setText("");
            return;
        }
        


        try {
            Connection conn = DBConnection.getConnection();
            String query = "INSERT INTO member (username, password, no_hp, saldo_menit) VALUES (?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, username);
            ps.setString(2, password);
            ps.setLong(3, Long.parseLong(noHp));
            ps.setInt(4, saldoMenit);

            ps.executeUpdate();

            alertLabel.setForeground(java.awt.Color.GREEN);
            alertLabel.setText("*Akun berhasil dibuat!");
            alertLabel.setVisible(true);
            txtUser.setText("");
            txtPhoneNumber.setText("");

        } catch (SQLException e) {
            if (e.getMessage().contains("no_hp")) {
                alertLabel.setText("*No HP sudah terdaftar!");
            } else {
                alertLabel.setText("*Username sudah dipakai!");
            }
            alertLabel.setForeground(java.awt.Color.RED);
            alertLabel.setVisible(true);
        }
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
            loadMember("");
            txtSearch.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        loadMember(txtSearch.getText().trim());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMember.getSelectedRow();
        
        if (selectedRow == -1 ){
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Pilih Member Yang mau di Hapus!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                    );
            return;
        }
        
        String username = tblMember.getValueAt(selectedRow, 1).toString();
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                 "Hapus member " + username + "?",
            "Konfirmasi Hapus",
        javax.swing.JOptionPane.YES_NO_OPTION);
                
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                Connection conn = DBConnection.getConnection();
                PreparedStatement ps = conn.prepareStatement("DELETE FROM member WHERE username = ?");
                ps.setString(1,username);
                ps.executeUpdate();
                
                loadMember("");
            }catch (SQLException e){
                System.out.println("Erorr" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteMemberActionPerformed

    private void rb1JamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1JamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1JamActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        int tambahMenit = 0;
        
        if (rb1Jam.isSelected()){
            tambahMenit = 60;
        }else if (rb3Jam.isSelected()){
            tambahMenit = 180;
        }else if (rb5Jam.isSelected()){
            tambahMenit = 300;
        }else if (rb10Jam.isSelected()){
            tambahMenit = 600;
        }else{
                javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih Durasi Dulu CUY!",
                "Peringatan!!",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String code = generateKode();
        
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                    "INSERT INTO redeem_code (kode, tambah_menit) VALUES (?,?)" 
            );
            
            ps.setString(1, code);
            ps.setInt(2, tambahMenit);
            ps.executeUpdate();

            txtCode.setText(code);
        
        loadKode();
        }catch (SQLException e) {
            System.out.println("Erorr : " +  e.getMessage());
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void rb3JamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3JamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3JamActionPerformed

    private void btnRefreshCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCodeActionPerformed
        // TODO add your handling code here:
        loadKode();

    }//GEN-LAST:event_btnRefreshCodeActionPerformed
    
    private void loadMember(String keyword) {
        DefaultTableModel model = (DefaultTableModel) tblMember.getModel();
        model.setRowCount(0);

        try {
            Connection conn = DBConnection.getConnection();
            String query;
            PreparedStatement ps;

            if (keyword.isEmpty()) {
                // Tampilkan semua member
                query = "SELECT * FROM member";
                ps = conn.prepareStatement(query);
            } else {
                // Filter by username
                query = "SELECT * FROM member WHERE username LIKE ?";
                ps = conn.prepareStatement(query);
                ps.setString(1, "%" + keyword + "%");
            }

            ResultSet rs = ps.executeQuery();
            int no = 1;

            while (rs.next()) {
                int saldoMenit = rs.getInt("saldo_menit");
                int jam = saldoMenit / 60;
                int menit = saldoMenit % 60;
                String waktu = jam + " jam " + menit + " menit";

                model.addRow(new Object[]{
                    no++,
                    rs.getString("username"),
                    rs.getString("no_hp"),
                    waktu
                });
            }

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }    

    private String generateKode(){
        String chars = "ABCEDFGHIJKLMNOPQRSTUVWXYZ0123456789";
        Random random = new Random();
        StringBuilder code = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            code.append(chars.charAt(random.nextInt(chars.length())));
        }
        return code.toString();
    }
    private void loadKode() {
        DefaultTableModel model = (DefaultTableModel) tblCode.getModel();
        model.setRowCount(0);
        
        try {
            Connection conn = DBConnection.getConnection();
            ResultSet rs = conn.prepareStatement("SELECT * FROM redeem_code").executeQuery();
            int no = 1;
            
            while (rs.next()) {
                int menit = rs.getInt("tambah_menit");
                String durasi = (menit / 60)+ "Jam";
                
                model.addRow(new Object[]{
                    no++,
                    rs.getString("kode"),
                    durasi,
                    rs.getString("status") 
                });
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel alertLabel;
    private javax.swing.ButtonGroup bgDuration;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnBuatMember;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnLihatMember;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefreshCode;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTambahBilling;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JPanel panelAddBilling;
    private javax.swing.JPanel panelCreateAccount;
    private javax.swing.JPanel panelSeeMember;
    private javax.swing.JRadioButton rb10Jam;
    private javax.swing.JRadioButton rb1Jam;
    private javax.swing.JRadioButton rb3Jam;
    private javax.swing.JRadioButton rb5Jam;
    private javax.swing.JTable tblCode;
    private javax.swing.JTable tblMember;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
